const statesCity = {
    'SD-KH': ['Khartoum ', 'Jabal Awliya ', 'Khartoum Bahri ', 'Omdurman ', 'Om Badaa ', 'KasKararisala ', 'Sharq an-Nil'],
    'SD-DC': ['Zalingi', 'Wadi Salih', 'Nertiti', 'Mukjar', 'Azum', 'Um Dukhun', 'Rokirro', 'Bindisi'],
    'SD-DN': ['El Fasher', 'Al Waha', 'El Lait Jar Al Nabi', 'Dar El Salam', 'Kutum', 'Kebkabiya', 'El Malha', 'Sarf Omra', 'Um Kedada', 'Um Brou', 'Mellit', 'Karnoi', 'Al Tina', 'Alseraf', 'AlKoma', 'Kalamando', 'Tawila'],
    'SD-DE': ["Ad-Du'ain", 'Bahr El Arab', 'Yassin', 'Abu Karinka', 'Adila', 'Abu Jabra', 'Assalaya', 'El Ferdous', "Schearia"],
    'SD-DS': ['Nyala Municipality', 'Nyala North', 'Al Salam', 'Kas', 'Ed Al-fursan', 'Belil', 'Rahid Al-Bardi', 'Talas', 'Gereida', 'Bram', 'Natika', 'Marshang', 'Sharq Al Jabal', 'As Sinta', 'Katila', 'Um Dafuq', 'Al Wihdah', 'Ar Raddum', 'Damsu', 'Shattaayah', 'Kim'],
    'SD-DW': ['El Geneina', 'Foro Baranga', 'Beida', 'Kreinik', 'Habila', 'Sirba', 'Kalabs', 'Jebel Moon'],
    'SD-GD': ['El Gadarif Municipality', 'Wasat Al Qadarif', 'Ar Rahad', 'Al Fao', 'Al Fashaga', 'Al BUtanah', "Gala'a El-Nahal", 'Al Mafazah', 'Basundah', 'Al Quraisha', 'Al Galabat Ash-Shargiah', 'Al Qalabat Al Gharbyah'],
    'SD-GK': ['Abu Zabad', 'Ghubaysh', 'Al Khowiy', 'Al-adeyah', 'Abyei', 'Lagawa', 'Wad Banda', 'As-Sunt', 'Al Meerm', 'Keilk', 'Babanusa', 'Ad-Dabab', 'As-Salam', 'En-Nehoud'],
    'SD-GZ': ['Greater Medani', 'South Al Jazirah', 'East Al Jazirah', 'Umm Al-Qura', '24 Al Qurashi', 'Al Hasahisa', 'Al Kamlein', 'Al Managil'],
    'SD-KA': ['Kassala', 'West Kassala Rural', 'East Kassala Rural', 'Halfa El Jadida', 'Nahr Atbara', 'Khashm El-Girba', 'Wad El-Hileo', "Hsmashkoriab", 'Telkuk', 'Aroma', 'shamal Al-delta'],
    'SD-KN': ['Shikan', 'Jabr At Sheikh', 'Sodery', 'Bara', 'Gharb(West) Bura', 'Am Ruwaba', 'Umm Dam Haj Ahmad', 'Ar-Rahad Abudanka'],
    'SD-KS': ['Kadugli', 'Al Dalanj', 'Rashad', 'Abu Jubaiha', "Al 'Abbasiyah", 'Talodi', 'Umm Dorin', 'Al Bram', 'Al Quoz', 'Heiban', 'Al Rif Al Sharqiyah', 'Habila', 'Abu Karshula', 'Lami', 'At-Tadamon', 'Al Liri', 'Qadir'],
    'SD-NB': ['Damazine', 'Ar Roseires', 'Al kormok', 'Qeissan', 'Bau', 'At Tadamon'],
    'SD-NO': ['Dongola', 'Delgo', 'Wadi Halfa', 'Merowe', 'Ad-Dabbah', 'Al Burgaig', 'Al Goled'],
    'SD-NR': ['Ad Damir', 'Al Matammah', 'Shendi', 'Atbara', 'Berber', 'Abu Hamad', 'Al Buhara'],
    'SD-NW': ['Rabak', 'Kosti', 'Ad Duwaim', 'Al Gutaynah', 'Al Jabalayn', 'Tandalti', 'As Salam', 'Um Ramta', 'Guli'],
    'SD-RS': ['Port Sudan', 'Suakin', 'Al Qanb Wal-Olib', 'Sinkat', 'Haya', 'Dardarib', 'Tokar', "Jebel Al Ma'adin", 'Aqeiq', 'Halaib'],
    'SD-SI': ['Singa', 'Sennar', 'Abu Hujar', 'Ad Dindir', 'El-Suki', 'Sharaq(East) Sennar', 'Ad-Dali Wal-Mazmom']
};